### ISSUE TITLE
General Todo List

### ISSUE THREAD

**Issue by Navnedia** [Navnedia/Link-Shortener#1]
- [ ] Refactor the short link controller to make the code cleaner and more reusable.
- [ ] Switch document models to typegoose?
- [ ] Do I need to use indexes for MongoDB?
- [ ] Change some of the generic object types to more strongly typed references.
- [ ] Add users and authentication.
- [ ] Build a simple front end.
- [ ] Make front end responsive.
- [ ] Upload & update design documentation.
- [ ] Update project license.
- [ ] Update README.
- [ ] Add any needed comments for code clarity.
- [ ] Clean up extra comments and commented out code.
- [ ] Improve front end to be more responsive for Mobile.
- [ ] Add low security message
- [ ] Move more of the error messages into a config to make it configurable.
- [ ] Maybe set Defaults for properties like the name to untitled before sending the API response.
- [ ] Handle route without specified ID (Show error)
